; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
monitor_speed = 115200
monitor_filters = time, default
lib_deps = 
	cyijun/ESP32MQTTClient@^1.1.1
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	bogde/HX711@^0.7.5
	miguelbalboa/MFRC522@^1.4.12
	adafruit/Adafruit AS7341@^1.4.1
	adafruit/Adafruit TCS34725@^1.4.4
	you-010/GY33_Colour_Sensor@^1.1.2
extra_scripts = post:merge.py
build_flags =
	-D FW_VERSION=\"${sysenv.FW_VERSION}\"
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

[env:gateway]
build_flags =
	${env.build_flags}
	-D DEVICE_ROLE_GATEWAY

[env:probe]
build_flags =
	${env.build_flags}
	-D DEVICE_ROLE_PROBE

[env:standalone]
build_flags =
	${env.build_flags}
	-D DEVICE_ROLE_STANDALONE
